#!/usr/bin/env bash
# install nginx web server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chown -R "$USER:$USER" /var/www/html
echo "Holberton School" >> /var/www/html/index.html
sudo service nginx start
